In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('/content/student_placement_synthetic.csv')

In [ ]:
df.head(3)

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
0,ECE,Tier-3,6.70,0,7.6,4.4,49.5,3.7,6.4,0.3,1,4,4,3,2,1,1,14.75
1,Chemical,Tier-2,5.70,0,5.4,7.9,72.0,8.3,6.3,1.9,0,4,0,0,0,0,0,NaN
2,EE,Tier-2,7.19,0,5.6,6.8,79.1,7.4,4.4,5.2,1,3,2,1,2,0,1,19.06

In [ ]:
df.tail(3)

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
99997,EE,Tier-2,7.94,0,4.9,9.1,55.1,6.1,3.5,5.2,0,2,1,0,1,2,1,17.24
99998,ME,Tier-3,6.63,0,5.0,8.0,65.0,5.7,6.2,0.2,1,4,2,0,0,1,1,17.01
99999,ECE,Tier-1,7.00,0,2.8,5.3,64.5,5.7,5.7,3.4,0,2,2,2,0,1,1,14.98

In [ ]:
df.dtypes

branch                        object
college_tier                  object
cgpa                         float64
backlogs                       int64
coding_skills                float64
dsa_score                    float64
aptitude_score               float64
communication_skills         float64
ml_knowledge                 float64
system_design                float64
internships                    int64
projects_count                 int64
certifications                 int64
hackathons                     int64
open_source_contributions      int64
extracurriculars               int64
placement_status               int64
salary_package_lpa           float64
dtype: object

In [ ]:
df.shape

(100000, 18)

In [ ]:
df.isnull().sum()

branch                           0
college_tier                     0
cgpa                             0
backlogs                         0
coding_skills                    0
dsa_score                        0
aptitude_score                   0
communication_skills             0
ml_knowledge                     0
system_design                    0
internships                      0
projects_count                   0
certifications                   0
hackathons                       0
open_source_contributions        0
extracurriculars                 0
placement_status                 0
salary_package_lpa           31525
dtype: int64

In [ ]:
df = df.drop('salary_package_lpa',axis=1)

In [ ]:
df.shape

(100000, 17)

In [ ]:
df.columns

Index(['branch', 'college_tier', 'cgpa', 'backlogs', 'coding_skills',
       'dsa_score', 'aptitude_score', 'communication_skills', 'ml_knowledge',
       'system_design', 'internships', 'projects_count', 'certifications',
       'hackathons', 'open_source_contributions', 'extracurriculars',
       'placement_status'],
      dtype='object')

In [ ]:
df.describe()

,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000
mean,7.206381,0.547010,5.995147,5.500711,64.990511,5.990614,4.508752,4.008210,1.095040,2.397280,1.49985,0.745840,0.450990,1.151100,0.684750
std,0.925235,0.862727,1.496302,1.781961,11.990892,1.496552,1.968278,1.778405,0.940264,1.242829,1.11407,0.884189,0.671061,0.965162,0.464618
min,4.000000,0.000000,1.000000,1.000000,20.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,6.580000,0.000000,5.000000,4.300000,56.800000,5.000000,3.200000,2.800000,0.000000,1.000000,1.00000,0.000000,0.000000,0.000000,0.000000
50%,7.210000,0.000000,6.000000,5.500000,65.000000,6.000000,4.500000,4.000000,1.000000,2.000000,1.00000,0.000000,0.000000,1.000000,1.000000
75%,7.830000,1.000000,7.000000,6.700000,73.100000,7.000000,5.900000,5.200000,2.000000,3.000000,2.00000,1.000000,1.000000,2.000000,1.000000
max,10.000000,3.000000,10.000000,10.000000,100.000000,10.000000,10.000000,10.000000,3.000000,5.000000,4.00000,3.000000,2.000000,3.000000,1.000000

In [ ]:
le = LabelEncoder()
df['branch'] = le.fit_transform(df['branch'])
df['college_tier'] = le.fit_transform(df['college_tier'])

In [ ]:
df.head(10)

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status
0,3,2,6.70,0,7.6,4.4,49.5,3.7,6.4,0.3,1,4,4,3,2,1,1
1,2,1,5.70,0,5.4,7.9,72.0,8.3,6.3,1.9,0,4,0,0,0,0,0
2,4,1,7.19,0,5.6,6.8,79.1,7.4,4.4,5.2,1,3,2,1,2,0,1
3,0,1,6.48,0,5.2,3.1,48.4,5.0,1.1,6.7,1,4,3,0,0,0,0
4,1,1,6.71,1,5.9,4.7,61.2,4.3,2.7,2.8,1,2,0,3,0,1,1
5,1,2,6.21,1,6.7,6.5,69.9,5.0,4.0,5.2,2,3,3,2,0,1,1
6,1,2,7.91,0,7.0,3.9,61.5,6.7,4.9,2.2,2,5,2,1,0,3,1
7,5,2,6.95,0,6.1,6.0,44.4,5.5,4.5,6.3,1,2,1,1,1,0,0
8,0,1,7.03,0,5.1,2.5,54.7,6.4,6.2,3.2,1,3,0,3,0,1,1
9,4,1,7.34,3,4.7,6.2,78.8,5.9,6.7,5.2,1,2,1,1,0,0,1

In [ ]:
df.tail(10)

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status
99990,5,2,8.03,0,3.4,8.6,63.7,4.4,3.1,1.0,1,3,2,3,0,1,1
99991,1,2,7.18,0,7.7,7.3,44.0,6.4,2.4,2.2,1,2,3,0,1,0,1
99992,2,1,6.84,0,8.4,4.6,53.6,7.3,5.5,1.0,0,3,3,0,0,2,1
99993,6,1,6.54,1,3.5,6.5,55.0,6.7,1.4,6.6,1,4,1,0,0,1,1
99994,5,0,7.99,0,9.2,3.6,45.2,6.3,4.0,3.9,1,2,1,1,0,1,1
99995,5,2,6.08,0,3.1,5.4,67.4,4.3,9.1,3.8,2,3,2,0,0,3,0
99996,5,2,7.46,0,4.8,6.8,59.5,7.6,5.6,2.4,1,2,3,0,1,0,1
99997,4,1,7.94,0,4.9,9.1,55.1,6.1,3.5,5.2,0,2,1,0,1,2,1
99998,6,2,6.63,0,5.0,8.0,65.0,5.7,6.2,0.2,1,4,2,0,0,1,1
99999,3,0,7.00,0,2.8,5.3,64.5,5.7,5.7,3.4,0,2,2,2,0,1,1

In [ ]:
df['placement_status'].value_counts()

placement_status
1    68475
0    31525
Name: count, dtype: int64

In [ ]:
x = df.drop('placement_status',axis=1)
y = df['placement_status']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,stratify=y,random_state=42)

In [ ]:
model = LogisticRegression()
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
x_train_predict = model.predict(x_train)
train_accuracy = accuracy_score(x_train_predict, y_train)
print(train_accuracy)

0.6982875

In [ ]:
x_test_predict = model.predict(x_test)
test_accuracy = accuracy_score(x_test_predict, y_test)
print(test_accuracy)

0.69785

In [ ]:
df.shape

(100000, 17)

In [ ]:
new_data = (2,1,5.7,0,5.4,7.9,72.0,8.3,6.3,1.9,0,4,0,0,0,0)

In [ ]:
new_array = np.asarray(new_data)
print(new_array)

[ 2.   1.   5.7  0.   5.4  7.9 72.   8.3  6.3  1.9  0.   4.   0.   0.
  0.   0. ]

In [ ]:
reshape = new_array.reshape(1,-1)
print(reshape)

[[ 2.   1.   5.7  0.   5.4  7.9 72.   8.3  6.3  1.9  0.   4.   0.   0.
   0.   0. ]]

In [ ]:
pre = model.predict(reshape)
print(pre)

[1]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [ ]:
if pre[0] == 0:
  print('Keep trying')
else:
  print('congrats, you have Placed')

congrats, you have Placed